import type { Metadata } from 'next'
import React from 'react'
import './globals.css'
import ClientLayout from '@/components/ClientLayout'

export const metadata: Metadata = {
  title: 'My Qiita',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col">
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  )
}
